routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('plantilla');
});


Route::resource('peliculas', App\Http\Controllers\PeliculasController::class);
Route::resource('categorias',  App\Http\Controllers\CategoriasController::class);

app/Models/Categorias.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Categorias extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $fillable = ['nombre','sinopsis','director','calificacion','estreno','id_peliculas'];
}

app/Models/Peliculas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Peliculas extends Model
{
    use HasFactory;
    protected $fillable = ['pelicula'];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/CategoriasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Categorias;
use App\Models\Peliculas;
use Illuminate\Validation\Rule;
class CategoriasController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $categorias = Categorias::select('categorias.id','nombre','sinopsis','director','calificacion','estreno','pelicula')
        ->join('peliculas','peliculas.id','=','categorias.id_peliculas')->get();
        $peliculas = Peliculas::all();
        return view('categorias',compact('categorias','peliculas'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $categoria = new Categorias($request->input());
        $categoria->saveOrFail();
        return redirect()->route('categorias.index')->with('success','Pelicula Creada');
        /**$request->validate([
            'calificacion' => 'required|numeric|between:1,10',
        ]);
        $categoria = new Categorias($request->input());
        $categoria->saveOrFail();
        return redirect()->route('categorias.index')->with('success', 'Categoría creada');*/
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $categoria = Categorias::find($id);
        $peliculas = Peliculas::all();
        return view('editCategorias',compact('categoria','peliculas'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $categoria = Categorias::find($id);
        $categoria->fill($request->input())->saveOrFail();
        return redirect()->route('categorias.index')->with('success','Pelicula actualizada');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $categoria = Categorias::find($id);
        $categoria->delete();
        return redirect()->route('categorias.index')->with('success','Pelicula Eliminada');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/PeliculasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Peliculas;

class PeliculasController extends Controller
{
    public function index()
    {
        $peliculas = Peliculas::all();
        return view('peliculas',compact('peliculas'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $request->validate([
            'pelicula' => 'required|unique:peliculas,pelicula|max:50',
        ]);
    
        $pelicula = new Peliculas($request->input());
        $pelicula->saveOrFail();    
        return redirect()->route('peliculas.index')->with('success', 'Categoría Creada');
    }
    

    public function show(string $id)
    {
        $pelicula = Peliculas::find($id);
        return view('editPelicula',compact('pelicula'));
    }

    public function edit(string $id)
    {
        //
    }

    public function update(Request $request, string $id)
    {
        $pelicula = Peliculas::find($id);
        $pelicula->fill($request->input())->saveOrFail();
        return redirect()->route('peliculas.index')->with('success','Categoría Actualizada');
    }

    public function destroy(string $id)
    {
        $pelicula = Peliculas::find($id);
        $pelicula->delete();
        return redirect()->route('peliculas.index')->with('success','Categoría eliminada');
    }
}

resources/views/categorias.blade.php
@extends('plantilla')
@section('contenido')
@if($mensaje = Session::get('success'))
    <div class="row" id="divok">
        <div class="col-md-6 offset-md-3">
            <div class="alert alert-success">
                <i class="fa-solid fa-check"></i>  {{$mensaje}}
            </div>
        </div>
    </div>
@endif
    <div class="row mt-3">
        <div class="col-md-4 offset-md-4">
            <div class="d-grid mx-auto">
                <button class="btn btn-dark"  data-bs-toggle="modal" data-bs-target="#modalPeliculas">
                    <i class="fa-solid fa-circle-plus"></i> Añadir Pelicula
                </button>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-12 col-lg-8 offset-lg-2"> 
            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Pelicula</th>
                            <th>Sinopsis</th>
                            <th>Director</th>
                            <th>Calificación</th>
                            <th>Estreno</th>
                            <th>Categoria</th>
                            <th>Editar</th>
                            <th>Eliminar</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        @php $i=1; @endphp
                        @foreach($categorias as $row)
                        <tr>
                            <td>{{ $i++ }}</td>
                            <td>{{ $row->nombre }}</td>
                            <td>{{ $row->sinopsis }}</td>
                            <td>{{ $row->director }}</td>
                            <td>{{ $row->calificacion }}</td>
                            <td>{{ $row->estreno }}</td>
                            <td>{{ $row->pelicula }}</td>
                            <td>
                                <a href="{{ url('categorias',[$row]) }}" class="btn btn-warning"><i class="fa-solid fa-edit"></i></a>
                            </td>
                            <td>
                                <form method="POST" id="frm_{{$row->id}}" action="{{ route('categorias.destroy',$row->id)}}">
                                    @csrf
                                    @method('DELETE')   
                                    <button onclick="datos('{{ $row->id }}','{{ $row->categoria }}')" type="button" class="btn btn-danger"><i class="fa-solid fa-trash " data-bs-toggle="modal" data-bs-target="#modalEliminar"></i></button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalPeliculas" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Añadir Pelicula</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="frmPeliculas" method="POST" action="{{ url("categorias")}}">
                    @csrf
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-film"></i></span>
                        <input type="text" name="nombre" class="form-control" maxlength="50" placeholder="Nombre" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-comments"></i></span>
                        <input type="text" name="sinopsis" class="form-control" maxlength="150" placeholder="Sinopsis" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-user-tie"></i></span>
                        <input type="text" name="director" class="form-control" maxlength="50" placeholder="Director" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-hashtag"></i></span>
                        <input type="number" name="calificacion"  step="any" class="form-control" maxlength="50" placeholder="Calificacion" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-calendar-days"></i></span>
                        <input type="date" name="estreno" class="form-control" maxlength="50" placeholder="Estreno" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-globe"></i></span>
                       <select name="id_peliculas" class="form-select" required>
                            <option value="">Categorias XD</option>
                            @foreach($peliculas as $row)
                            <option value="{{ $row->id}}">{{$row->pelicula}}</option>
                            @endforeach
                       </select>
                    </div>
                    <div class="d-grid col-6 mx-auto">
                        <button class="btn btn-success"><i class="fa-solid fa-floppy-disk"></i> Guardar</button>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
              <button type="button" id="btnCerrar" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
          </div>
        </div>
      </div>
      <div class="modal" tabindex="-1" id="modalEliminar">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title"><i class="fa-solid fa-warning"> </i> Eliminar</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>¿Segúro de eliminar la pelicula <label id="lbl_nombre"> </label> ?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fa-solid fa-ban"></i> Cancelar</button>
              <button id="btnEliminar" type="button" class="btn btn-warning"><i class="fa-solid fa-check"></i> Si, eliminar pelicula</button>
            </div>
          </div>
        </div>
      </div>
    
@endsection 
@section('js')
@vite('resources/js/alertas.js')
@endsection

resources/views/editCategorias.blade.php
@extends('plantilla')
@section('contenido')
<div class="row mt-3">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-header bg-dark text-white">Editar Pelicula</div>
            <div class="card-body">
                <form id="frmPeliculas" method="POST" action="{{ url("categorias",[$categoria])}}">
                    @csrf
                    @method('PUT')
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-film"></i></span>
                        <input type="text" name="nombre" value="{{$categoria->nombre}}" class="form-control" maxlength="50" placeholder="Nombre" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-comments"></i></span>
                        <input type="text" name="sinopsis" value="{{$categoria->sinopsis}}" class="form-control" maxlength="150" placeholder="Sinopsis" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-user-tie"></i></span>
                        <input type="text" name="director" value="{{$categoria->director}}" class="form-control" maxlength="50" placeholder="Director" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-hashtag"></i></span>
                        <input type="number" name="calificacion" value="{{$categoria->calificacion}}" class="form-control" maxlength="50" placeholder="Calificacion" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-calendar-days"></i></span>
                        <input type="date" name="estreno" value="{{$categoria->estreno}}" class="form-control" maxlength="50" placeholder="Estreno" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-globe"></i></span>
                       <select name="id_peliculas" class="form-select" required>
                            <option value="">Categorias XD</option>
                            @foreach($peliculas as $row)
                                @if ($row->id == $categoria->id_peliculas)
                                    <option selected value="{{$row->id}}">{{ $row->pelicula}}</option>
                                @else
                                <option value="{{$row->id}}">{{ $row->pelicula}}</option>
                                
                                @endif
                            @endforeach
                       </select>
                    </div>
                    <div class="d-grid col-6 mx-auto">
                        <button class="btn btn-success"><i class="fa-solid fa-floppy-disk"></i> Guardar</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/editPelicula.blade.php
@extends('plantilla')
@section('contenido')
<div class="row mt-3">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-header bg-dark text-white">Editar Categoria</div>
            <div class="card-body">
                <form id="frmPeliculas" method="POST" action="{{ url("peliculas",[$pelicula])}}">
                    @method('PUT')
                    @csrf
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-globe"></i></span>
                        <input type="text" name="pelicula" value="{{$pelicula->pelicula}}" class="form-control" maxlength="50" placeholder="Categoria" required>
                    </div>
                    <div class="d-grid col-6 mx-auto">
                        <button class="btn btn-success"><i class="fa-solid fa-floppy-disk"></i> Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/peliculas.blade.php
@extends('plantilla')
@section('contenido')
@if($mensaje = Session::get('success'))
    <div class="row" id="divok">
        <div class="col-md-6 offset-md-3">
            <div class="alert alert-success">
                <i class="fa-solid fa-check"></i>  {{$mensaje}}
            </div>
        </div>
    </div>
@endif
    <div class="row mt-3">
        <div class="col-md-4 offset-md-4">
            <div class="d-grid mx-auto">
                <button class="btn btn-dark"  data-bs-toggle="modal" data-bs-target="#modalPeliculas">
                    <i class="fa-solid fa-circle-plus"></i> Añadir Categoria
                </button>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-12 col-lg-8 offset-lg-2"> 
            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Categoria</th>
                            <th>Editar</th>
                            <th>Eliminar</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        @php $i=1; @endphp
                        @foreach($peliculas as $row)
                        <tr>
                            <td>{{ $i++ }}</td>
                            <td>{{ $row->pelicula }}</td>
                            <td>
                                <a href="{{ url('peliculas',[$row]) }}" class="btn btn-warning"><i class="fa-solid fa-edit"></i></a>
                            </td>
                            <td>
                                <form method="POST" id="frm_{{$row->id}}" action="{{ route('peliculas.destroy',$row->id)}}">
                                    @csrf
                                    @method('DELETE')   
                                    <button onclick="datos('{{ $row->id }}','{{ $row->pelicula }}')" type="button" class="btn btn-danger"><i class="fa-solid fa-trash " data-bs-toggle="modal" data-bs-target="#modalEliminar"></i></button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalPeliculas" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Añadir Categoria</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="frmPeliculas" method="POST" action="{{ url("peliculas")}}">
                    @csrf
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="fa-solid fa-globe"></i></span>
                        <input type="text" name="pelicula" class="form-control" maxlength="50" placeholder="Categoria" required>
                    </div>
                    <div class="d-grid col-6 mx-auto">
                        <button class="btn btn-success"><i class="fa-solid fa-floppy-disk"></i> Guardar</button>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
              <button type="button" id="btnCerrar" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
          </div>
        </div>
      </div>
      <div class="modal" tabindex="-1" id="modalEliminar">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title"><i class="fa-solid fa-warning"> </i> Eliminar</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>¿Segúro de eliminar la categoría <label id="lbl_nombre"> </label> ?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fa-solid fa-ban"></i> Cancelar</button>
              <button id="btnEliminar" type="button" class="btn btn-warning"><i class="fa-solid fa-check"></i> Si, Eliminar categoría</button>
            </div>
          </div>
        </div>
      </div>
    
@endsection 
@section('js')
@vite('resources/js/alertas.js')
@endsection

resources/views/plantilla.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Peliculas Laravel </title>
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/all.min.css') }}" rel="stylesheet">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">LaraPeliculas <i class="fa-regular fa-file-video"></i></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/peliculas">Categorias</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/categorias">Peliculas</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container-fluid">
        @yield('contenido')
      </div>
</body>
@yield('js')
</html>